/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '手撕pinia源码（二）：实现defineStore.html': typeof import('./src/components/docsTemplate/手撕pinia源码（二）：实现defineStore.html.vue')['default']
    '手撕pinia源码（三）：实现pinia内置方法.html': typeof import('./src/components/docsTemplate/手撕pinia源码（三）：实现pinia内置方法.html.vue')['default']
    '手撕pinia源码（一）： pinia的使用.html': typeof import('./src/components/docsTemplate/手撕pinia源码（一）： pinia的使用.html.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
